add extension methods option
ClydeDz/horoscope-nuget pull request #13
Opened 2021-10-14 12:46 UTC by lfmundim

## What has changed and why?
Adding extension methods to make it easier to use directly from a `DateTime` object

Closes #12 

## Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the `CONTRIBUTING` document.
- [X] My code follows the code style of this project.
- [X] My change requires to update the console app that outlines how to use the NuGet package.
- [X] My change requires a change to the documentation in the `README` file.
- [X] I have updated the documentation in the `README` file accordingly.
- [X] I have updated the version number in the [`Horoscope.nuspec`](https://github.com/ClydeDz/horoscope-nuget/blob/master/Src/Horoscope.nuspec) file using the [SemVer](https://semver.org/) format.
- [X] I have added `<summary>` comments to all publicly accessible methods, classes, etc.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-10-18 06:16 UTC, ClydeDz reviewed
Hi, @lfmundim,

Thanks for contributing! This is a good idea and your changes look good. Before I merge this PR, would you be able to please add the following release updates as well so that we can release it straight away? 

- Update the version and release notes. [Example commit here](https://github.com/ClydeDz/horoscope-nuget/commit/ebb73dc0abb37938c7993568f8a2cc40cc1db7e8). The current version is 1.0.0. so that would make the next one 1.1.0. based on [these guidelines](https://semver.org/). 
- Add the extension method examples to the [test console application](https://github.com/ClydeDz/horoscope-nuget/tree/master/Src/Horoscope.TestConsole) that's in the same project. The purpose of the test console application was to show the user how to use the NuGet package. Following the existing pattern, you would create a new class for the extension method and then just reference it from `program.cs`. 
- I think it would be a good idea to also update [the Readme file](https://github.com/ClydeDz/horoscope-nuget/blob/master/README.md) accordingly. 

After you've made the above changes, you should be able to check a few more boxes in the checklist in this PR. :)

Thanks!

2021-10-26 17:31 UTC, lfmundim commented
Hello! Sorry for the delay,  the requested changes are done :)

2021-10-28 05:25 UTC, ClydeDz requested changes
Thanks for making the updates as per my previous comment, @lfmundim. Just noticed two lines weren't updated (inline comment added) - would you mind taking care of that and then we're good to go?

2021-10-28 05:25 UTC, ClydeDz commented on Src/Horoscope/Horoscope.csproj
>      <FileVersion>1.0.0.0</FileVersion>
This might need to be updated as well, @lfmundim, as per [this commit](https://github.com/ClydeDz/horoscope-nuget/commit/ebb73dc0abb37938c7993568f8a2cc40cc1db7e8).

2021-10-29 13:21 UTC, lfmundim commented on Src/Horoscope/Horoscope.csproj
>      <FileVersion>1.0.0.0</FileVersion>
My bad! that slipped

2021-10-30 04:15 UTC, ClydeDz approved these changes

2021-10-30 04:22 UTC, merged

2021-10-30 04:34 UTC, ClydeDz commented
Changes have been deployed to NuGet.org. Thanks for contributing, @lfmundim! 🎉